service: bot-infrastructure

# Add the serverless-webpack plugin
plugins:
  - serverless-plugin-parent
  - serverless-webpack
  - serverless-prune-plugin

provider:
  name: aws

resources:
  Resources:
    ACLTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: "uid"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "uid"
            KeyType: "HASH"
        ProvisionedThroughput:
          # Use auto scaling - not set in config atm, manually set
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.services.acl_table_name}
